- name: Create Tomcat user
  user:
    name: tomcat
    shell: /bin/false
    create_home: no
- name: Create Tomcat Directory
  file:
    path: /opt/tomcat
    state: directory
    mode: "0755"
    owner: tomcat
    group: tomcat
- name: Set /opt/tomcat as Tomcat user's home directory
  user:
    name: tomcat
    home: /opt/tomcat
    shell: /bin/false
    state: present      
- name: Download Tomcat 9.0.93
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.93/bin/apache-tomcat-9.0.93.tar.gz"
    dest: "/tmp/apache-tomcat-9.0.93.tar.gz"
- name: Extract Tomcat
  unarchive:
    src: "/tmp/apache-tomcat-9.0.93.tar.gz"
    dest: /opt
    remote_src: yes
    owner: tomcat
    group: tomcat
- name: Create symbolic link for Tomcat
  file:
    src: "/opt/apache-tomcat-9.0.93"
    dest: /opt/tomcat
    state: link
    owner: tomcat
    group: tomcat
    force: yes
- name: Make catalina.sh executable
  file:
    path: /opt/tomcat/bin/catalina.sh
    mode: "0755"
    owner: tomcat
    group: tomcat
